# Generated by Django 2.1.4 on 2018-12-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20181206_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lists.List'),
        ),
    ]
